import { Router } from 'express';
import { logAudit } from '../audit.js';
import { getOpportunityById } from '../data/opportunitiesStore.js';
import { getSegmentDetail } from '../data/segmentsStore.js';
import { getDashboardMetrics } from '../data/stubMetrics.js';

export const agentRouter = Router();

const STUB_RESPONSES = {
  default: 'This is a stub response from the Executive Insight Agent. In production, this would be generated by the multi-agent AI layer based on your prompt and current dashboard context.',
  'Show monthly revenue and cost trends': 'Monthly revenue has remained stable at approximately $35M, while medical cost shows a 2.1% increase over the last three months. PMPM is trending at $336. Recommendation: monitor high-cost segments.',
  'Rank LOBs based on revenue and cost performance': 'Ranking by margin: 1) Commercial (MLR 85%), 2) Medicare (MLR 90%), 3) Medicaid (MLR 94%). Commercial shows the strongest performance with lowest MLR.',
  'Identify top 5 margin recovery opportunities': 'Top 5: (1) Prior auth automation — $2.1M savings, (2) Care gap closure — $1.8M, (3) ER diversion — $1.5M, (4) Pharmacy utilization — $1.2M, (5) Inpatient length of stay — $0.9M.',
  'Summarize margin improvement story for board presentation': 'Year-over-year MLR improved from 91% to 90.2%. We have 47 identified opportunities with $12.5M potential savings; 8 approved and in execution. Key focus: prior authorization and care gaps.',
  'How can I recover margin in the next 90 days without hurting quality':
    'Here are focused actions that support margin recovery in the next 90 days while protecting quality:\n\n' +
    '**1. Prior authorization & utilization** — Automate routine prior auth and steer to high-value sites (e.g., ambulatory vs. inpatient where appropriate). This typically yields 1–2% medical cost reduction without cutting necessary care.\n\n' +
    '**2. Care gap closure** — Target HEDIS and quality-related gaps (e.g., diabetic eye exams, medication adherence). Closing gaps improves outcomes and often reduces avoidable cost (ER, admissions) in the same 90-day window.\n\n' +
    '**3. Pharmacy** — Encourage generics and preferred drugs where clinically appropriate; review high-cost specialty utilization. Savings are usually 2–4% of pharmacy spend with no compromise on needed therapy.\n\n' +
    '**4. Avoid blunt cuts** — Defer reductions that directly affect access or quality (e.g., network or benefit cuts). Focus on waste reduction, coding accuracy, and utilization management instead.\n\n' +
    '**5. Track quality and margin together** — Use the same 90-day dashboard for MLR/PMPM and key quality metrics (readmissions, avoidable ER). If a lever hurts quality, pause and refine.\n\n' +
    'In our current book, the top 5 identified opportunities (prior auth, care gaps, ER diversion, pharmacy, length of stay) represent about $7.5M in potential savings; prioritizing the first two can deliver early wins within 90 days while supporting quality.',
};

agentRouter.post('/prompt', (req, res) => {
  const { promptId, promptText, context } = req.body;
  const userId = req.headers['x-user-id'] || 'anonymous';
  const role = req.headers['x-user-role'] || 'viewer';

  if (!promptText && !promptId) {
    return res.status(400).json({ error: 'promptId or promptText required' });
  }

  const key = promptText || promptId;
  const responseText = STUB_RESPONSES[key] || STUB_RESPONSES.default;
  logAudit({ action: 'prompt_execution', userId, role, promptId, promptText: promptText || promptId, context });

  res.json({
    response: responseText,
    confidence: 0.85,
    sources: [],
  });
});

/** Build a detailed QnA response for opportunity-context questions (e.g. why avoidable admissions). Returns string or null. */
function buildOpportunityQnAResponse(opp, messageTrimmed) {
  const q = messageTrimmed.toLowerCase();
  const isAvoidableAdmissions =
    (opp.id === 'opp-1' || (opp.title && opp.title.toLowerCase().includes('inpatient'))) &&
    (/avoidable\s+admission|inpatient\s+admission|why.*avoidable|explain.*avoidable|consider.*avoidable/i.test(q) ||
      /why are.*admissions|what makes.*avoidable/i.test(q));

  if (isAvoidableAdmissions && opp.explainability) {
    const pop = opp.explainability.populationSegment || [];
    const drivers = opp.explainability.rootCauseKeyDrivers || [];
    const scale = opp.explainability.scale || [];
    const nextAction = opp.explainability.nextBestAction || '';
    const scaleLines = scale.map((s) => `- **${s.label}**: ${s.value}`).join('\n');

    return (
      `**Why inpatient admissions in this opportunity are considered avoidable**\n\n` +
      `**1. Primary drivers of avoidable admissions (for this population)**\n\n` +
      `For this opportunity we focus on members who:\n` +
      (pop.length ? pop.map((p) => `- ${p}`).join('\n') + '\n\n' : '') +
      `The main drivers of **avoidable** admissions in this group are: **${drivers.join('** and **')}**. ` +
      `These are factors that, if addressed with timely follow-up and care coordination, can prevent a portion of readmissions and unnecessary hospitalizations. ` +
      `Claims and utilization patterns show these drivers are present in a large share of the target population.\n\n` +
      `**2. Clinical necessity vs preventable causes**\n\n` +
      `- **Clinically necessary** admissions are those where hospitalization is required for acute illness, surgery, or safety (e.g. acute MI, stroke, severe infection). We are not targeting those.\n` +
      `- **Preventable or avoidable** admissions in this opportunity are those linked to: (a) **missed or delayed follow-up** after a prior discharge, (b) **medication confusion or non-adherence** that leads to decompensation, and (c) **lack of timely outpatient management** so that conditions that could be managed in the community escalate to admission. ` +
      `The data (e.g. 30-day readmission rate vs benchmark, and the population criteria above) are used to separate patterns that indicate **preventable** use from those that are clinically necessary.\n\n` +
      `**3. Patterns that indicate intervention opportunity**\n\n` +
      `The following patterns in this population indicate there is an **intervention opportunity**:\n` +
      (scaleLines ? scaleLines + '\n\n' : '') +
      `Specifically: a **30-day readmission rate above benchmark** suggests that a meaningful share of readmissions could be reduced with better transition-of-care and follow-up. ` +
      `Members **discharged in the last 90 days** with **multiple ED visits** but no consistent follow-up are at higher risk of avoidable readmission. ` +
      `These patterns are used to prioritize who gets the **next best action** (e.g. mandatory PCP follow-up within 7 days).\n\n` +
      `**4. Why these admissions are likely to recur without action**\n\n` +
      `Without action, the same drivers (missed follow-up, medication confusion, lack of outpatient management) continue. ` +
      `Members who have already had a recent hospitalization and ED use are at higher risk of another admission if they do not receive structured follow-up and support. ` +
      `Evidence and our own data show that **recurrence is likely** in this population without targeted intervention. ` +
      `The **next best action** for this opportunity is: **${nextAction}**. ` +
      `Implementing this reduces the chance of avoidable recurrence by closing gaps in follow-up and care coordination.\n\n` +
      `**Summary** — In this opportunity, inpatient admissions are considered avoidable when they occur in the defined population (e.g. CHF, recent discharge, multiple ED visits) and are driven by missed follow-up and medication-related issues rather than unavoidable clinical necessity. ` +
      `Patterns such as elevated readmission rate vs benchmark and high ED use without follow-up indicate intervention opportunity; without action, these admissions are likely to recur.`
    );
  }

  const isSpecificActionsQuestion =
    (opp.id === 'opp-1' || (opp.title && opp.title.toLowerCase().includes('inpatient'))) &&
    (/specific\s+actions|reduce\s+these\s+admissions|how\s+confident|expected\s+impact|actions\s+will\s+reduce|confidence.*impact|impact.*confidence/i.test(q) ||
      /what.*actions.*reduce|operationaliz/i.test(q));

  if (isSpecificActionsQuestion && opp.explainability) {
    const drivers = opp.explainability.rootCauseKeyDrivers || [];
    const nextAction = opp.explainability.nextBestAction || '';
    const confidencePct = Math.round((opp.confidenceScore || 0.88) * 100);
    const savingsM = (opp.estimatedSavings / 1e6).toFixed(2);
    const scale = opp.explainability.scale || [];
    const scaleMap = Object.fromEntries((scale || []).map((s) => [s.label, s.value]));

    return (
      `**What specific actions will reduce these admissions, and how confident are we in the impact?**\n\n` +
      `**1. Specific actions that will reduce admissions (operationalized quickly)**\n\n` +
      `- **Mandatory PCP follow-up within 7 days of discharge** — Make post-discharge follow-up a standard step for the target population (e.g. CHF, recent discharge, multiple ED visits). This can be rolled out within 2–4 weeks by updating discharge workflows and scheduling.\n` +
      `- **Medication reconciliation and simplified regimens at discharge** — Reduce medication confusion by reconciling prescriptions at discharge and, where appropriate, simplifying regimens. Pharmacy or care management can own this; can start within 2–3 weeks.\n` +
      `- **Post-discharge outreach (call or portal) within 48–72 hours** — Proactively contact high-risk members to confirm follow-up plans and address barriers. Care management or nurse triage can implement quickly.\n` +
      `- **Structured transition-of-care handoff to PCP** — Ensure the hospital sends a clear summary and follow-up plan to the PCP. Often achievable by aligning with existing transition-of-care processes.\n\n` +
      `**2. How each action addresses the root cause**\n\n` +
      `- **Missed follow-up** — Mandatory 7-day PCP follow-up and 48–72 hour outreach directly close the gap between discharge and first outpatient visit. The handoff to PCP ensures the PCP has context and can act.\n` +
      `- **Medication confusion** — Reconciliation at discharge and simplified regimens reduce dosing errors and non-adherence that lead to decompensation and readmission. Outreach calls can reinforce instructions and flag issues early.\n\n` +
      `**3. Expected impact and confidence level**\n\n` +
      `- **Expected impact:** For this opportunity we estimate **$${savingsM} M** in savings, driven by reducing excess readmissions in the target population (e.g. ${scaleMap['Members affected'] || '4,000'} members affected, 30-day readmission rate at ${scaleMap['30 day readmission rate'] || '17%'} vs benchmark ${scaleMap['Benchmark'] || '11%'}). A realistic target is a **2–4 percentage point** reduction in 30-day readmission rate in the first 12 months, which aligns with the addressable scope in the model.\n` +
      `- **Confidence level:** We are **${confidencePct}%** confident in this impact. The confidence reflects strength of evidence (e.g. ACSC definitions, transition-of-care literature), data quality on the target population, and the fact that these actions are well-aligned with the root causes (missed follow-up, medication confusion). Execution risk (e.g. adoption of 7-day follow-up) is the main uncertainty.\n\n` +
      `**4. Timeframe in which results should be visible**\n\n` +
      `- **30–60 days:** Early signals (e.g. % of discharges with a 7-day follow-up, outreach completion rate) should be visible once workflows are live.\n` +
      `- **90 days:** First impact on 30-day readmission rate can be measured; expect a modest improvement if actions are in place for most of the period.\n` +
      `- **6–12 months:** Full run-rate impact on readmissions and cost; use quarterly readmission and cost trends to track progress against the **$${savingsM} M** opportunity.\n\n` +
      `**Summary** — The main actions are: mandatory PCP follow-up within 7 days, medication reconciliation at discharge, post-discharge outreach within 48–72 hours, and structured handoff to PCP. Each directly addresses missed follow-up or medication confusion. We estimate **$${savingsM} M** impact with **${confidencePct}%** confidence; results can be monitored within 30–90 days, with full impact visible in 6–12 months. All of these can be operationalized quickly (within 2–4 weeks) with existing care management and discharge workflows.`
    );
  }

  if (opp.explainability && (/explain|why|what|how|drivers|cause|rationale/i.test(q))) {
    const pop = opp.explainability.populationSegment || [];
    const drivers = opp.explainability.rootCauseKeyDrivers || [];
    const nextAction = opp.explainability.nextBestAction || '';
    return (
      `**QnA in context of: ${opp.title}**\n\n` +
      `**Population:**\n` + (pop.length ? pop.map((p) => `- ${p}`).join('\n') + '\n\n' : '') +
      `**Root causes / key drivers:** ${drivers.join('; ')}.\n\n` +
      `**Next best action:** ${nextAction}.\n\n` +
      `For this opportunity, estimated savings are **$${(opp.estimatedSavings / 1e6).toFixed(2)} M** with **${(opp.confidenceScore * 100).toFixed(0)}%** confidence. ` +
      `The rationale and explainability above summarize why this opportunity is identified and what levers address it.`
    );
  }

  return null;
}

agentRouter.post('/chat', (req, res) => {
  const { message, sessionId, opportunityId, segmentId } = req.body;
  const userId = req.headers['x-user-id'] || 'anonymous';
  const role = req.headers['x-user-role'] || 'viewer';

  if (!message) {
    return res.status(400).json({ error: 'message required' });
  }

  const messageTrimmed = (message || '').trim();
  let responseText =
    STUB_RESPONSES[message] || STUB_RESPONSES[messageTrimmed] || STUB_RESPONSES.default;
  if (opportunityId) {
    const opp = getOpportunityById(opportunityId);
    if (opp) {
      const detailedQnA = buildOpportunityQnAResponse(opp, messageTrimmed);
      if (detailedQnA) {
        responseText = detailedQnA;
      } else {
        responseText = `[QnA in context of: "${opp.title}"] ${responseText} For this opportunity: estimated savings $${(opp.estimatedSavings / 1e6).toFixed(2)}M, confidence ${(opp.confidenceScore * 100).toFixed(0)}%. Risks and dependencies would be assessed by the full QnA agent in production.`;
      }
    }
  } else if (segmentId) {
    const seg = getSegmentDetail(segmentId);
    if (seg) {
      responseText = `[QnA in context of Segment: "${seg.name}"] ${responseText} This segment represents ${seg.memberCount.toLocaleString()} members. Key risk: ${seg.riskCharacteristics[0]}.`;
    }
  }
  logAudit({ action: 'chat', userId, role, message, sessionId, opportunityId, segmentId });

  res.json({
    response: responseText,
    sessionId: sessionId || `sess-${Date.now()}`,
    confidence: 0.85,
  });
});

/** Parse scenario text for "realization rate is X%" or "if the realization rate is 80%" etc. Returns target rate 0–100 or null. */
function parseRealizationRateFromScenario(scenario) {
  if (!scenario || typeof scenario !== 'string') return null;
  const trimmed = scenario.trim();
  const match = trimmed.match(/(?:realization\s+rate\s+(?:is|at|to|of)\s*)?(\d+)\s*%?/i) ||
    trimmed.match(/(\d+)\s*%\s*realization/i);
  if (match) {
    const pct = parseInt(match[1], 10);
    if (pct >= 0 && pct <= 100) return pct;
  }
  return null;
}

/** Parse scenario for "reduce MLR from X% to Y%" or "MLR from 90% to 87%". Returns { fromPct, toPct } or null. */
function parseMLRReductionFromScenario(scenario) {
  if (!scenario || typeof scenario !== 'string') return null;
  const trimmed = scenario.trim();
  // e.g. "reduce MLR from 90% to 87%", "MLR from 90% to 87%", "what should I do to reduce MLR from 90% to 87%"
  const match = trimmed.match(/mlr\s+from\s+(\d+)\s*%\s*to\s+(\d+)\s*%/i) ||
    trimmed.match(/reduce\s+mlr\s+from\s+(\d+)\s*%\s*to\s+(\d+)\s*%/i) ||
    trimmed.match(/(\d+)\s*%\s*to\s+(\d+)\s*%.*mlr/i);
  if (match) {
    const fromPct = parseInt(match[1], 10);
    const toPct = parseInt(match[2], 10);
    if (fromPct >= 0 && fromPct <= 100 && toPct >= 0 && toPct <= 100 && toPct < fromPct) {
      return { fromPct, toPct };
    }
  }
  return null;
}

agentRouter.post('/whatif', (req, res) => {
  const { opportunityId, scenario } = req.body;
  const userId = req.headers['x-user-id'] || 'anonymous';
  logAudit({ action: 'whatif_simulation', userId, opportunityId, scenario });

  const opp = opportunityId ? getOpportunityById(opportunityId) : null;
  const metrics = getDashboardMetrics({});
  const oppAgg = metrics.opportunity || {};
  const currentRealizationRate = oppAgg.addressable > 0
    ? (oppAgg.realizable / oppAgg.addressable) * 100
    : 72;
  const targetRealizationPct = parseRealizationRateFromScenario(scenario);

  if (opp && targetRealizationPct != null && scenario && /realization\s+rate|net\s+savings/i.test(scenario)) {
    // What-if: potential net savings if realization rate changes
    const currentNetSavings = opp.estimatedSavings;
    const addressableForOpp = currentRealizationRate > 0
      ? currentNetSavings / (currentRealizationRate / 100)
      : currentNetSavings / 0.72;
    const newNetSavings = Math.round(addressableForOpp * (targetRealizationPct / 100));
    const delta = newNetSavings - currentNetSavings;
    const response =
      `**What-if: Potential net savings at ${targetRealizationPct}% realization rate**\n\n` +
      `For this opportunity (**${opp.title}**), the current potential net savings are based on a realization rate of **${Math.round(currentRealizationRate)}%**. ` +
      `That yields **$${(currentNetSavings / 1e6).toFixed(2)} M** in net savings for this opportunity.\n\n` +
      `If the realization rate increases from **${Math.round(currentRealizationRate)}%** to **${targetRealizationPct}%**:\n\n` +
      `- **Addressable opportunity** (underlying scope) is unchanged: **$${(addressableForOpp / 1e6).toFixed(2)} M**.\n` +
      `- **New potential net savings** at ${targetRealizationPct}% realization: **$${(newNetSavings / 1e6).toFixed(2)} M**.\n` +
      `- **Change**: ${delta >= 0 ? '+' : ''}$${(delta / 1e6).toFixed(2)} M (${delta >= 0 ? 'increase' : 'decrease'} of **$${Math.abs(delta).toLocaleString()}**).\n\n` +
      `So **at ${targetRealizationPct}% realization, the potential net savings for this opportunity would be $${(newNetSavings / 1e6).toFixed(2)} M**.\n\n` +
      `This assumes the addressable scope and other drivers stay the same; only the share we capture (realization rate) changes.`;
    return res.json({
      response,
      projections: {
        currentRealizationRatePct: Math.round(currentRealizationRate),
        targetRealizationRatePct: targetRealizationPct,
        currentNetSavings,
        newNetSavings,
        addressableForOpp,
        delta,
      },
      assumptions: scenario,
    });
  }

  const org = metrics.organizational || {};
  const mlrReduction = parseMLRReductionFromScenario(scenario);
  if (mlrReduction && scenario && /reduce\s+mlr|mlr\s+from|what\s+should\s+I\s+do/i.test(scenario)) {
    const currentMlr = org.mlr ?? 90;
    const totalMedicalCost = org.totalMedicalCost ?? 0;
    const totalRevenue = org.totalRevenue ?? 0;
    const targetMlrPct = mlrReduction.toPct;
    const targetCostAtMlr = totalRevenue > 0 ? (targetMlrPct / 100) * totalRevenue : 0;
    const requiredCostReduction = Math.max(0, Math.round(totalMedicalCost - targetCostAtMlr));
    const realizable = oppAgg.realizable ?? 0;

    const response =
      `**What should I do to reduce MLR from ${mlrReduction.fromPct}% to ${mlrReduction.toPct}%?**\n\n` +
      `**Current situation**\n\n` +
      `- **Current MLR**: **${currentMlr}%** (medical cost as % of revenue).\n` +
      `- **Target MLR**: **${targetMlrPct}%** — a **${mlrReduction.fromPct - targetMlrPct} percentage point** improvement.\n` +
      `- **Total medical cost** (current): **$${(totalMedicalCost / 1e6).toFixed(2)} M**.\n` +
      `- **Total revenue**: **$${(totalRevenue / 1e6).toFixed(2)} M**.\n\n` +
      `**Gap to close**\n\n` +
      `To reach **${targetMlrPct}%** MLR, medical cost must be at or below **$${(targetCostAtMlr / 1e6).toFixed(2)} M**. ` +
      `That means you need to **reduce medical cost by **$${(requiredCostReduction / 1e6).toFixed(2)} M** (or achieve equivalent margin improvement through revenue/cost levers).\n\n` +
      `**What you should do**\n\n` +
      `1. **Execute the opportunity pipeline** — You have **$${(realizable / 1e6).toFixed(2)} M** in **realizable** savings from identified opportunities (addressable after realization). Prioritize high-confidence, high-savings opportunities (e.g. prior auth automation, care gap closure, avoidable ED redirect) and track execution so realized savings hit the bottom line.\n\n` +
      `2. **Utilization and clinical levers** — Focus on: **avoidable inpatient admissions**, **duplicate services**, **low-value care**, and **non-emergent ED visits**. These map directly to cost reduction without cutting necessary care. Use the explainability and rationale on each opportunity to target the right populations and interventions.\n\n` +
      `3. **PMPM and unit cost** — Drive down **PMPM** through utilization management, site-of-care steerage, and pharmacy management. Even a small PMPM reduction across the book compounds to meaningful MLR improvement.\n\n` +
      `4. **Track and reforecast** — Monitor MLR monthly; re-run this what-if as you lock in savings to see how much of the **$${(requiredCostReduction / 1e6).toFixed(2)} M** gap is closed. If you realize **$${(realizable / 1e6).toFixed(2)} M** of the pipeline, you will have closed a significant portion of the gap toward **${targetMlrPct}%** MLR.\n\n` +
      `**Summary** — To reduce MLR from **${mlrReduction.fromPct}%** to **${targetMlrPct}%**, you need **$${(requiredCostReduction / 1e6).toFixed(2)} M** in medical cost reduction. Prioritize executing the identified opportunity pipeline (realizable **$${(realizable / 1e6).toFixed(2)} M**) and utilization levers; track progress and reforecast regularly.`;

    return res.json({
      response,
      projections: {
        currentMlr,
        targetMlrPct,
        requiredCostReduction,
        targetCostAtMlr,
        realizable,
      },
      assumptions: scenario,
    });
  }

  // Fallback: generic projection
  const baseSavings = opp ? opp.estimatedSavings : 1000000;
  const response =
    (scenario ? `**Scenario:** ${scenario}\n\n` : '') +
    `**Projections (baseline):**\n` +
    `- Year 1: **$${(baseSavings / 1e6).toFixed(2)} M** savings\n` +
    `- Year 2: **$${(baseSavings * 1.1 / 1e6).toFixed(2)} M** savings\n` +
    `- Year 3: **$${(baseSavings * 1.2 / 1e6).toFixed(2)} M** savings\n\n` +
    `**Tailored what-if examples:**\n` +
    `- *Realization rate:* "What will be the potential net savings if the realization rate is 80%?"\n` +
    `- *MLR reduction:* "What should I do to reduce MLR from 90% to 87%?"`;
  res.json({
    response,
    projections: {
      year1: { savings: baseSavings, marginImpact: 0.2 },
      year2: { savings: baseSavings * 1.1, marginImpact: 0.22 },
      year3: { savings: baseSavings * 1.2, marginImpact: 0.24 },
    },
    assumptions: scenario || 'Baseline scenario',
  });
});

const PLANNER_POST_DISCHARGE_ANALYSIS = `# Opportunity: Missed Post-Discharge Follow-Up (Cross-Condition)

## Line(s) of Business (LOB)
- **All** (Medicare Advantage, Medicaid, Commercial)

---

## What AI Detects

The AI Opportunity Mining Platform identifies this opportunity when the following conditions are met:

- Any **inpatient discharge** event
- **No outpatient follow-up visit within 7 days** of discharge
- A **sharp spike in utilization** (ED visits, observation stays, or readmissions) occurring between **days 10–30 post-discharge**

These patterns are detected using claims timelines, encounter data, and utilization sequencing rather than simple rate-based reports.

---

## Why This Opportunity Is Attractive

- **Cross-LOB applicability**  
  The same pattern appears consistently across Medicare, Medicaid, and Commercial populations.

- **Easy to operationalize**  
  Interventions (auto-scheduling follow-ups, discharge-to-PCP handoff, care manager outreach) are well understood and already supported by most care management teams.

- **Strong evidence base**  
  Early post-discharge follow-up is one of the most consistently validated levers for reducing avoidable utilization and improving outcomes.

---

## Typical Impact

- **Readmissions decrease** due to early issue identification and medication reconciliation
- **Quality scores improve**, particularly transition-of-care and follow-up measures
- **Scales quickly across conditions**, including CHF, COPD, diabetes, pneumonia, and surgical discharges

---

## Executive Summary

> Missed post-discharge follow-up is a high-confidence, cross-LOB opportunity where simple, timely interventions can reduce avoidable readmissions, protect quality performance, and deliver fast, repeatable margin improvement.`;

function plannerAnalyze(message) {
  const m = (message || '').toLowerCase();
  const isPostDischarge =
    m.includes('post discharge') ||
    m.includes('post-discharge') ||
    (m.includes('follow up') && (m.includes('discharge') || m.includes('missed'))) ||
    (m.includes('follow-up') && (m.includes('discharge') || m.includes('missed')));
  if (isPostDischarge) {
    return {
      title: 'Missed Post-Discharge Follow-Up (Cross-Condition)',
      description: PLANNER_POST_DISCHARGE_ANALYSIS,
      analysisDescription: PLANNER_POST_DISCHARGE_ANALYSIS,
      estimatedSavings: 1200000,
      confidenceScore: 0.85,
      implementationComplexity: 'medium',
      tags: ['planner-created', 'post-discharge', 'follow-up'],
      lob: ['Medicare Advantage', 'Medicaid', 'Commercial'],
    };
  }
  return {
    title: message && message.length > 10 ? message.slice(0, 80) : 'New margin improvement opportunity',
    description: message || 'Guided opportunity from Planner agent. Refine title and description as needed.',
    analysisDescription: null,
    estimatedSavings: 500000,
    confidenceScore: 0.7,
    implementationComplexity: 'medium',
    tags: ['planner-created'],
    lob: [],
  };
}

agentRouter.post('/planner', (req, res) => {
  const { message } = req.body;
  const userId = req.headers['x-user-id'] || 'demo-user';
  logAudit({ action: 'planner_create', userId, message });

  const suggested = plannerAnalyze(message);
  res.json({ suggested });
});
